@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.feedApp.jpa.FeedMetaData#getComment()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.feedApp.jpa.FeedMetaData",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_976040029 { 
   	label=feedApp
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1310698646 { 
   	label=service
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1030494298 { 
   	label=FeedService
	labeljust=l
	fillcolor=white
	style=filled
   
   FeedService1452183805XXXcreateFeedMetaData1774260304[
	label="+ createFeedMetaData()"
	style=filled
	fillcolor=white
	tooltip="FeedService

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_85800176 { 
   	label=jpa
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1353367272 { 
   	label=FeedMetaData
	labeljust=l
	fillcolor=white
	style=filled
   
   FeedMetaData1717777885XXXgetComment0[
	label="+ getComment()"
	style=filled
	fillcolor=white
	tooltip="FeedMetaData

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_886611655 { 
   	label=controller
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_2009748692 { 
   	label=FeedController
	labeljust=l
	fillcolor=white
	style=filled
   
   FeedController1164448852XXXcreateFeedMetaData1774260304[
	label="+ createFeedMetaData()"
	style=filled
	fillcolor=white
	tooltip="FeedController

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
FeedController1164448852XXXcreateFeedMetaData1774260304 -> FeedService1452183805XXXcreateFeedMetaData1774260304;
FeedService1452183805XXXcreateFeedMetaData1774260304 -> FeedMetaData1717777885XXXgetComment0;
    
}
@enduml